# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';
in
linkFarm name [
  {
    name = "raylib_zig-6.0.0-KE8REMNkBQCpxwqT9ubVNf5aEOcWRUVIaH2sgt_sDDoZ.tar.gz";
    path = fetchZig {
      name = "raylib_zig";
      url = "git+https://github.com/raylib-zig/raylib-zig?ref=devel#58f3c0fa328fc9ff48d17c2c3771ab9c5114aaa6";
      hash = "sha256-eaKQFy9sZ+h4JZV4jpA5sTX24VNxdbbt3OMZWF+HrII=";
    };
  }
  {
    name = "raylib-6.0.0-whq8uCSwLgWWeF3ec3dbG6Rr36SLFL-s2WJ1Q_2E22Bb.tar.gz";
    path = fetchZig {
      name = "raylib";
      url = "git+https://github.com/raysan5/raylib#6.0";
      hash = "sha256-fbcvBqRORAJsX1w0JmNwQ0Att/DEfZZlYZibHur1ZyM=";
    };
  }
  {
    name = "N-V-__8AALShqgXkvqYU6f__FrA22SMWmi2TXCJjNTO1m8XJ.tar.gz";
    path = fetchZig {
      name = "xcode_frameworks";
      url = "https://pkg.machengine.org/xcode-frameworks/8a1cfb373587ea4c9bb1468b7c986462d8d4e10e.tar.gz";
      hash = "sha256-FzjO+d3kOEFG/Bxp3ayIVTfugUzlJ/nJ1zPw2h3ZpVM=";
    };
  }
  {
    name = "N-V-__8AAHvybwBw1kyBGn0BW_s1RqIpycNjLf_XbE-fpLUF.tar.gz";
    path = fetchZig {
      name = "raygui";
      url = "git+https://github.com/raysan5/raygui#3b2855842ab578a034f827c38cf8f62c042fc983";
      hash = "sha256-6nG04hG5GRUSOp0jrfBwG3hSCVC85SstgiCTjsthQfk=";
    };
  }
  {
    name = "N-V-__8AAJl1DwBezhYo_VE6f53mPVm00R-Fk28NPW7P14EQ.tar.gz";
    path = fetchZig {
      name = "emsdk";
      url = "git+https://github.com/emscripten-core/emsdk#4.0.9";
      hash = "sha256-89ke6Nk0BZgE5LvmuvNpBqKKIEH9FM+nXhCziIZqlQs=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqApRAACspTbAZnuNKWIzfWzSYgYkb2nWAXZ-tqqt.tar.gz";
    path = fetchZig {
      name = "zemscripten";
      url = "git+https://github.com/zig-gamedev/zemscripten#3fa4b778852226c7346bdcc3c1486e875a9a6d02";
      hash = "sha256-yc9fQLDVzT8D05yYZV7QuCcADZpnNriljglBQfDe9nI=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqEtQAAB_1tPdqJsxQIqXxvvklcFu6VN5p6ANy8hw.tar.gz";
    path = fetchZig {
      name = "zemscripten";
      url = "git+https://github.com/zig-gamedev/zemscripten#70bdafc473be2131445bb6fd977fe7cb92fd0f5f";
      hash = "sha256-mt/g7bwLW3AaZyDq2G11LUnl/Z2cHAYKp9Io8qKi2tg=";
    };
  }
  {
    name = "zclay-0.2.2-Ej1rkP3RAACYZGzQB5NGPaqfySgKfO26NYk5Ja6Z15gC.tar.gz";
    path = fetchZig {
      name = "zclay";
      url = "git+https://github.com/johan0A/clay-zig-bindings#e0286c488a303b93501944ccde10730cc74ecd58";
      hash = "sha256-lB0Qp3SIq2X1voyai9l70Yapl4RjSOjrczHKT5h6cRM=";
    };
  }
  {
    name = "N-V-__8AALPgZwA7tLqRlkCCL7OrkEhj4xZ3y_0FxgR42t0W.tar.gz";
    path = fetchZig {
      name = "clay";
      url = "git+https://github.com/nicbarker/clay?ref=v0.14#b25a31c1a152915cd7dd6796e6592273e5a10aac";
      hash = "sha256-6LpQgJ+qjnyNpIfzzitZ0srVuvNI4r5wArVUUjQndZM=";
    };
  }
  {
    name = "box2d_zig-0.0.0-B_mA0owZAAAk2NewcIApGvVNllbk5gYIozBXLvmI6GSs.tar.gz";
    path = fetchZig {
      name = "box2d_zig";
      url = "git+https://github.com/fish1/box2d-zig#c4e399fa936fdc397174554e168042463b485f72";
      hash = "sha256-N0V4R3iTMMegFeAWo9K0ZAzqo1SK+Krh+th1VanPFDM=";
    };
  }
  {
    name = "N-V-__8AAII1NQDjMkqg9_eX2bAPlt8E86FYCOrLKlu5Bo--.tar.gz";
    path = fetchZig {
      name = "box2d";
      url = "git+https://github.com/erincatto/box2d#56edae79f2949d86142b03450d5d60f63bcf5a6f";
      hash = "sha256-v2+5u3karQ0E1qgN+piYnMbkST/iT97kn3/hlcd7NQY=";
    };
  }
  {
    name = "zflecs-0.2.0-dev-1PN3yvUPQQBUdlukoUPPTpW5NLhkagNIEtOq0C0S3bmf.tar.gz";
    path = fetchZig {
      name = "zflecs";
      url = "git+https://github.com/zig-gamedev/zflecs#9c2771cf0cae508db622821bb7deac6e9370a9de";
      hash = "sha256-1UUQO87uDiLIa/CMnzW8ZSdIQOod/8XZQXdbYxqB2rM=";
    };
  }
]
